export const REGISTRATION_SUCCESS = 'REGISTRATION _SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_STARTED = 'AUTH_STARTED';
export const CLOSE_ERROR_MESSAGE = 'CLOSE_ERROR_MESSAGE';

export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';
export const GET_DATA_STARTED = 'GET_DATA_STARTED';
export const GET_CLAIMS_SUCCESS = 'GET_CLAIMS_SUCCESS';

export const BY_POST_NEW_CLAIM_SUCCESS = 'BY_POST_NEW_CLAIM_SUCCESS';
export const BY_POST_DATA_FAILURE = 'BY_POST_DATA_FAILURE';
export const BY_POST_DATA_STARTED = 'BY_POST_DATA_STARTED';

export const GET_CURRENT_CLAIM_SUCCESS = 'GET_CURRENT_CLAIM_SUCCESS';

export const UPDATE_CURRENT_CLAIM_SUCCESS = 'UPDATE_CURRENT_CLAIM_SUCCESS';
export const UPDATE_CURRENT_CLAIM_STARTED = 'UPDATE_CURRENT_CLAIM_STARTED';
export const UPDATE_CURRENT_CLAIM_FAILURE = 'UPDATE_CURRENT_CLAIM_FAILURE';

export const CLOSE_CURRENT_CLAIM = 'CLOSE_CURRENT_CLAIM';

export const LOGOUT = 'LOGOUT';

export const UPDATE_REGISTRATION_FORM = 'UPDATE_REGISTRATION_FORM';
export const OPEN_CREATE_NEW_CLAIM_FORM = 'OPEN_CREATE_NEW_CLAIM_FORM';

export const GET_USER_DATA_SUCCESS = 'GET_USER_DATA_SUCCESS';
export const GET_USER_DATA_FAILURE = 'GET_USER_DATA_FAILURE';
export const GET_USER_DATA_STARTED = 'GET_USER_DATA_STARTED';
