export const REGISTRATION_SUCCESS = 'REGISTRATION _SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const AUTH_FAILURE = 'AUTH_FAILURE';
export const AUTH_STARTED = 'AUTH_STARTED';
export const CLOSE_ERROR_MESSAGE = 'CLOSE_ERROR_MESSAGE';

export const UPDATE_REGISTRATION_FORM = 'UPDATE_REGISTRATION_FORM';

export const OPEN_CREATE_NEW_CLAIM_FORM = 'OPEN_CREATE_NEW_CLAIM_FORM';
export const CREATE_NEW_CLAIM = 'CREATE_NEW_CLAIM';

export const CHANGE_STATUS_OF_INCOMING_CLAIM = 'CHANGE_STATUS_OF_INCOMING_CLAIM';

export const UPDATE_CURRENT_TABLE_ELEMENT = 'UPDATE_CURRENT_TABLE_ELEMENT';

export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';
export const GET_DATA_STARTED = 'GET_DATA_STARTED';
export const GET_CLAIMS_SUCCESS = 'GET_CLAIMS_SUCCESS';

export const POST_NEW_CLAIM_SUCCESS = 'POST_NEW_CLAIM_SUCCESS';
export const POST_DATA_FAILURE = 'POST_DATA_FAILURE';
export const POST_DATA_STARTED = 'POST_DATA_STARTED';

export const GET_CURRENT_CLAIM_SUCCESS = 'GET_CURRENT_CLAIM_SUCCESS';
