const Data = [
  {
    key: 1,
    title: 'Figma smart web system for to build',
    created: '12/04/2021',
    type: 'Hardware',
    status: 'declined',
    actions: 'Browse',
  },
  {
    key: 2,
    title: 'Figma smart web system for to build',
    created: '12/04/2021',
    type: 'Hardware',
    status: 'declined',
    actions: 'Browse',
  },
  {
    key: 3,
    title: 'Figma smart web system for to build',
    created: '12/04/2021',
    type: 'Hardware',
    status: 'declined',
    actions: 'Browse',
  },
  {
    key: 4,
    title: 'Figma smart web system for to build',
    created: '12/04/2021',
    type: 'Hardware',
    status: 'declined',
    actions: 'Browse',
  },
  {
    key: 5,
    title: 'Figma smart web system for to build',
    created: '12/04/2021',
    type: 'Hardware',
    status: 'declined',
    actions: 'Browse',
  },
  {
    key: 6,
    title: 'Figma smart web system for to build',
    created: '12/04/2021',
    type: 'Hardware',
    status: 'declined',
    actions: 'Browse',
  },
  {
    key: 7,
    title: 'Figma smart web system for to build',
    created: '12/04/2021',
    type: 'Hardware',
    status: 'declined',
    actions: 'Browse',
  },
  {
    key: 8,
    title: 'Figma smart web system for to build',
    created: '12/04/2021',
    type: 'Hardware',
    status: 'declined',
    actions: 'Browse',
  },
  {
    key: 9,
    title: 'Figma smart web system for to build',
    created: '12/04/2021',
    type: 'Hardware',
    status: 'declined',
    actions: 'Browse',
  },
  {
    key: 10,
    title: 'Figma smart web system for to build',
    created: '12/04/2021',
    type: 'Hardware',
    status: 'declined',
    actions: 'Browse',
  },
  {
    key: 11,
    title: 'Figma smart web system for to build',
    created: '12/04/2021',
    type: 'Hardware',
    status: 'declined',
    actions: 'Browse',
  },
];

export default Data;
